name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-18.04
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl  'https://api-goats.plaync.com/search/l2m/items?page=1&size=15&from_enchant_level=0&to_enchant_level=11&sale=true' -H 'Origin:https://lineage2m.plaync.com'  | jq . > price.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push